name: Branch Checks
description: Action to check code consistency

runs:
  using: composite
  steps:
    - name: Check Formatting
      shell: bash
      run: bun run format:check

    - name: Lint Code
      shell: bash
      run: bun run lint

    - name: Type Check
      shell: bash
      run: bun run typecheck

    # Add additional branch checks here.
    # i.e. Translations, security, and any other additional check
